stages:
  - base
  - build
  - docker

variables:
  DOCKER_DRIVER: overlay2
  CONTAINER_REPO: seismic-gitlab.eastus.cloudapp.azure.com:5005
  BASE_IMAGE: $CI_REGISTRY_IMAGE/base
  BASE_IMAGE_TAG: $BASE_IMAGE:latest
  CI_APPLICATION_TAG: $(echo $CI_COMMIT_SHA | cut -c1-8)

base_image:
  image: docker:stable
  stage: base
  services:
    - name: docker:stable-dind
      entrypoint:
        - dockerd-entrypoint.sh
  before_script:
    - apk add --update openssh-client make ca-certificates openssl python git bash
  script:
    - mkdir -p ~/.ssh
    - ssh-keyscan git.microquake.org >> /root/.ssh/known_hosts¬
    - chmod -R 700 ~/.ssh
    - eval $(ssh-agent -s) && ssh-add <(echo "$SSH_PRIVATE_KEY") && git submodule update --init --recursive'
    - update-ca-certificates

    - docker login -u deploy -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build . -t $BASE_IMAGE_TAG -t $BASE_IMAGE:$(echo $CI_COMMIT_SHA | cut -c1-8) --build-arg SSH_PRIVATE_KEY -f Dockerfile.baseimage
    - docker push $BASE_IMAGE_TAG
    - docker push $BASE_IMAGE:$(echo $CI_COMMIT_SHA | cut -c1-8)
