stages:
  - build
  - docker
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  CI_APPLICATION_TAG: $(echo ${CI_COMMIT_SHA} | cut -c1-8)
  KUBE_VERSION: v1.12.1

spp:
  image: docker:stable
  stage: build
  services:
    - name: docker:stable-dind
      entrypoint:
        - dockerd-entrypoint.sh
  before_script:
    - apk add --update openssh-client make ca-certificates openssl python git bash
  script:
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'

    - mkdir -p ~/.ssh
    - chmod -R 700 ~/.ssh
    - ssh-keyscan -H git.microquake.org >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git submodule update --init --recursive
    - update-ca-certificates

    - docker login -u deploy -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build . -t $CI_REGISTRY_IMAGE/spp:latest -t $CI_REGISTRY_IMAGE/spp:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE/spp:$(echo $CI_COMMIT_SHA | cut -c1-8) --build-arg SSH_PRIVATE_KEY
    - docker push $CI_REGISTRY_IMAGE/spp:latest
    - docker push $CI_REGISTRY_IMAGE/spp:$(echo $CI_COMMIT_SHA | cut -c1-8)
    - docker push $CI_REGISTRY_IMAGE/spp:$CI_COMMIT_SHA

kube:
  image: docker:stable
  stage: deploy
  services:
    - name: docker:stable-dind
      entrypoint:
        - dockerd-entrypoint.sh
  before_script:
    - apk add --update openssh-client make ca-certificates openssl python git bash
  script:
    - wget https://storage.googleapis.com/kubernetes-release/release/${KUBE_VERSION}/bin/linux/amd64/kubectl
    - chmod +x kubectl
    - echo "$KUBE" > admin.conf
    - ./kubectl --kubeconfig admin.conf set image deployment.v1.apps/seismic-platform *=registry.microquake.org/rio-tinto/seismic-processing-platform/spp:$(echo $CI_COMMIT_SHA | cut -c1-8) --record=true
  only:
    refs:
      - master

# test:
#   image: docker:stable
#   stage: test
#   retry: 2
#   services:
#     - name: docker:stable-dind
#       entrypoint:
#         - dockerd-entrypoint.sh
#   before_script:
#     - apk add --update openssh-client make ca-certificates openssl python git bash
#   script:
#     - wget https://storage.googleapis.com/kubernetes-release/release/${KUBE_VERSION}/bin/linux/amd64/kubectl
#     - chmod +x kubectl
#     - echo "$KUBE" > admin.conf
#     - ./kubectl --kubeconfig admin.conf set image deployment.v1.apps/seismic-platform-test *=registry.microquake.org/rio-tinto/seismic-processing-platform/spp:$(echo $CI_COMMIT_SHA | cut -c1-8) --record=true
#     - ./kubectl --kubeconfig admin.conf exec $(./kubectl --kubeconfig admin.conf get pod -l "app=seismic-platform-test" --namespace=default -o jsonpath='{.items[0].metadata.name}') -- poetry run pytest ./tests --workers 4
test:
  image: registry.microquake.org/rio-tinto/seismic-processing-platform/spp:$CI_COMMIT_SHA
  stage: test
  retry: 2
  script:
    - bash -c ". /ve/bin/activate ; poetry install"
    - bash -c ". /ve/bin/activate ; pytest tests"
