version: "3.5"

networks:
  spp-network:
    external: true

services:
#  automatic:
#    networks:
#      - spp-network
#    image: registry.microquake.org/rio-tinto/seismic-processing-platform/spp:latest
#    hostname: automatic
#    container_name: automatic
#    external_links:
#      - redisdb
#    volumes:
#      - $SPP_COMMON/:/data/common
#      - $SPP_CONFIG/:/data/config
#      - ./spp:/app/spp
#    environment:
#      SPP_COMMON: "/data/common"
#      SPP_CONFIG: "/data/config"
#    command: bash -c "seismic_platform automatic"
#    working_dir:
#      /app/bin
#    restart: always
#    tty: true
#

#  interactive:
#    networks:
#      - spp-network
#    image: registry.microquake.org/rio-tinto/seismic-processing-platform/spp:latest
#    hostname: interactive
#    container_name: interactive
#    external_links:
#      - redisdb
#    volumes:
#      - $SPP_COMMON/:/data/common
#      - $SPP_CONFIG/:/data/config
#      - ./spp:/app/spp
#    environment:
#      SPP_COMMON: "/data/common"
#      SPP_CONFIG: "/data/config"
#    command: bash -c "seismic_platform interactive"
#    working_dir:
#      /app/bin
#    restart: always
#    tty: true
#
  event_connector:
    networks:
      - spp-network
    image: registry.microquake.org/rio-tinto/seismic-processing-platform/spp:latest
    hostname: event_connector
    container_name: event_connector
    external_links:
      - redisdb
    depends_on:
      - spp-postgres
    volumes:
      - $SPP_COMMON/:/data/common
      - $SPP_CONFIG/:/data/config
      - ./spp:/app/spp
    environment:
      SPP_COMMON: "/data/common"
      SPP_CONFIG: "/data/config"

    working_dir:
      /app/spp/data_connector
    tty: true

  spp-postgres:
    networks:
      - spp-network
    image: timescale/timescaledb:latest-pg11
    hostname: spp-postgres
    container_name: spp-postgres
    ports:
      - "5433:5432"
    environment:
      TIMESCALEDB_TELEMETRY: "off"
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/timescale-initdb.sql:/docker-entrypoint-initdb.d/timescale-initdb.sql
      - ./data/grafana-initdb.sql:/docker-entrypoint-initdb.d/grafana-initdb.sql
      - .tmp/postgres:/data/postgres
      - 'postgresql_data:/bitnami/postgresql'

volumes:
    mi2: {}
