version: "3.5"

services:
  spp-postgres:
    image: timescale/timescaledb-postgis:1.3.1-pg11
    hostname: spp-postgres
    container_name: spp-postgres
    ports:
      - "5433:5432"
    environment:
      TIMESCALEDB_TELEMETRY: "off"
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/timescale-initdb.sql:/docker-entrypoint-initdb.d/timescale-initdb.sql
      - ./data/grafana-initdb.sql:/docker-entrypoint-initdb.d/grafana-initdb.sql
