[tool.poetry]
name = "seismic-processing-platform"
version = "0.1.0"
description = ""
authors = ["Reza Jelveh <reza.jelveh@toptal.com>"]

[tool.poetry.dependencies]
python = "3.7.0"
future = "*"
lxml = "*"
matplotlib = "*"
numpy = "*"
obspy = "*"
pymongo = "*"
pyparsing = "*"
scipy = "*"
scikit-fmm = "*"
cython = "*"
prometheus-client = "*"
avro = "*"
fastavro = "*"
pathos = "*"
pyyaml = "*"
toolz = "*"
pytz = "*"
msgpack = "*"
dynaconf = "*"
ipython = "*"
redis = "*"
confluent-kafka = "*"
kafka-python = "*"
tqdm = "*"
tenacity = "*"
apscheduler = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
autopep8 = "*"
numpy = "*"
