[sdist]
keep-temp = 1
dist-dir = "dist/source"

[tox]
minversion = "3.4.0"
requires = ["tox-venv", "setuptools >= 30.0.0"]

[tool.poetry]
name = "spp"
version = "0.1.0"
authors = ["Jean-Phillipe Mercier", "Reza Jelveh"]
license = "GPL-3.0"
description = "Python library for processing of seismic data"
keywords = ["seismology", "mining" ]
homepage = "https://api.microquake.org"
repository = "https://git.microquake.org"

[tool.poetry.dependencies]
python = "^3.6 || ^3.7"
future = "*"
lxml = "*"
matplotlib = "*"
numpy = "*"
obspy = "*"
pymongo = "*"
pyparsing = "*"
scipy = "*"
scikit-fmm = "*"
cython = "*"
prometheus-client = "*"
avro = "*"
fastavro = "*"
pathos = "*"
pyyaml = "*"
toolz = "*"
pytz = "*"
msgpack = "*"
dynaconf = "*"
ipython = "*"
redis = "*"
confluent-kafka = "*"
kafka-python = "*"
tqdm = "*"
tenacity = "*"
apscheduler = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
autopep8 = "*"
numpy = "*"
