
ims_connector:
  minimum_time_offset: 120          # minimum time offset from the time of the
                                    # request in seconds
  period: 120                        # frequency between each run in seconds
  window_length: 1                  # length of chunk of data in seconds
  overlap: 0.1                      # overlap between the windows in seconds
  max_window_length: 90             # maximum length of data to request in seconds
  data_source:                      # describes the data source and base url
    type: remote
    location: http://10.95.64.12:8002/ims-database-server/databases/mgl
  filter:                           # filter to apply to the data. These value are the argument to pass to the Obspy
                                    # filter function "Stream.filter"
    type: highpass
    freq: 60                        # frequency
  taper:                            # argument of Obspy Trace.taper function
    type: cosine                    # tapering function to apply
    max_length: 0.01                # window length ideally this value should be significantly smaller than overlap

  multiprocessing:                  # options related to multiprocessing
    workers: 16                     # number of workers
