
data_ingestion:
  minimum_time_offset: 120          # minimum time offset from the time of the request in seconds
  frequency: 60                     # frequency between each run in seconds
  window_length: 1                  # length of chunk of data in seconds
  overlap: 0.1                      # overlap between the windows in seconds
  max_window_length: 90             # maximum length of data to request in seconds
  data_source:                      # describes the data source and base url
    type: remote,
    location: http://10.95.64.12:8002/ims-database-server/databases/mgl