[default]
test_data_location = 'https://permanentdbfilesstorage.blob.core.windows.net/permanentdbfilesblob/spp_test_data'
local_temp_test_data_location = '/tmp/'
single_run = false
debug_level = 0
debug_file_dir = './common'
