
type: UTC_offset                # either 'UTC_offset or 'time_zone'
time_zone_code: ULN             # time zone code. If type=time_zone, time_zone_code must be a valid pytz timezone
offset: 8                       # time offset in hours, ignored if type=time_zone