// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waveform.proto

package waveform;

public final class Waveform {
  private Waveform() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StreamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:waveform.Stream)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string time = 1;</code>
     */
    java.lang.String getTime();
    /**
     * <code>string time = 1;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>repeated .waveform.Trace traces = 2;</code>
     */
    java.util.List<waveform.Waveform.Trace> 
        getTracesList();
    /**
     * <code>repeated .waveform.Trace traces = 2;</code>
     */
    waveform.Waveform.Trace getTraces(int index);
    /**
     * <code>repeated .waveform.Trace traces = 2;</code>
     */
    int getTracesCount();
    /**
     * <code>repeated .waveform.Trace traces = 2;</code>
     */
    java.util.List<? extends waveform.Waveform.TraceOrBuilder> 
        getTracesOrBuilderList();
    /**
     * <code>repeated .waveform.Trace traces = 2;</code>
     */
    waveform.Waveform.TraceOrBuilder getTracesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code waveform.Stream}
   */
  public  static final class Stream extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:waveform.Stream)
      StreamOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Stream.newBuilder() to construct.
    private Stream(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Stream() {
      time_ = "";
      traces_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Stream(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              time_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                traces_ = new java.util.ArrayList<waveform.Waveform.Trace>();
                mutable_bitField0_ |= 0x00000002;
              }
              traces_.add(
                  input.readMessage(waveform.Waveform.Trace.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          traces_ = java.util.Collections.unmodifiableList(traces_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return waveform.Waveform.internal_static_waveform_Stream_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return waveform.Waveform.internal_static_waveform_Stream_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              waveform.Waveform.Stream.class, waveform.Waveform.Stream.Builder.class);
    }

    private int bitField0_;
    public static final int TIME_FIELD_NUMBER = 1;
    private volatile java.lang.Object time_;
    /**
     * <code>string time = 1;</code>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        time_ = s;
        return s;
      }
    }
    /**
     * <code>string time = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRACES_FIELD_NUMBER = 2;
    private java.util.List<waveform.Waveform.Trace> traces_;
    /**
     * <code>repeated .waveform.Trace traces = 2;</code>
     */
    public java.util.List<waveform.Waveform.Trace> getTracesList() {
      return traces_;
    }
    /**
     * <code>repeated .waveform.Trace traces = 2;</code>
     */
    public java.util.List<? extends waveform.Waveform.TraceOrBuilder> 
        getTracesOrBuilderList() {
      return traces_;
    }
    /**
     * <code>repeated .waveform.Trace traces = 2;</code>
     */
    public int getTracesCount() {
      return traces_.size();
    }
    /**
     * <code>repeated .waveform.Trace traces = 2;</code>
     */
    public waveform.Waveform.Trace getTraces(int index) {
      return traces_.get(index);
    }
    /**
     * <code>repeated .waveform.Trace traces = 2;</code>
     */
    public waveform.Waveform.TraceOrBuilder getTracesOrBuilder(
        int index) {
      return traces_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, time_);
      }
      for (int i = 0; i < traces_.size(); i++) {
        output.writeMessage(2, traces_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, time_);
      }
      for (int i = 0; i < traces_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, traces_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof waveform.Waveform.Stream)) {
        return super.equals(obj);
      }
      waveform.Waveform.Stream other = (waveform.Waveform.Stream) obj;

      boolean result = true;
      result = result && getTime()
          .equals(other.getTime());
      result = result && getTracesList()
          .equals(other.getTracesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
      if (getTracesCount() > 0) {
        hash = (37 * hash) + TRACES_FIELD_NUMBER;
        hash = (53 * hash) + getTracesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static waveform.Waveform.Stream parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static waveform.Waveform.Stream parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static waveform.Waveform.Stream parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static waveform.Waveform.Stream parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static waveform.Waveform.Stream parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static waveform.Waveform.Stream parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static waveform.Waveform.Stream parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static waveform.Waveform.Stream parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static waveform.Waveform.Stream parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static waveform.Waveform.Stream parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static waveform.Waveform.Stream parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static waveform.Waveform.Stream parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(waveform.Waveform.Stream prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code waveform.Stream}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:waveform.Stream)
        waveform.Waveform.StreamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return waveform.Waveform.internal_static_waveform_Stream_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return waveform.Waveform.internal_static_waveform_Stream_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                waveform.Waveform.Stream.class, waveform.Waveform.Stream.Builder.class);
      }

      // Construct using waveform.Waveform.Stream.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTracesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        time_ = "";

        if (tracesBuilder_ == null) {
          traces_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          tracesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return waveform.Waveform.internal_static_waveform_Stream_descriptor;
      }

      @java.lang.Override
      public waveform.Waveform.Stream getDefaultInstanceForType() {
        return waveform.Waveform.Stream.getDefaultInstance();
      }

      @java.lang.Override
      public waveform.Waveform.Stream build() {
        waveform.Waveform.Stream result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public waveform.Waveform.Stream buildPartial() {
        waveform.Waveform.Stream result = new waveform.Waveform.Stream(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.time_ = time_;
        if (tracesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            traces_ = java.util.Collections.unmodifiableList(traces_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.traces_ = traces_;
        } else {
          result.traces_ = tracesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof waveform.Waveform.Stream) {
          return mergeFrom((waveform.Waveform.Stream)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(waveform.Waveform.Stream other) {
        if (other == waveform.Waveform.Stream.getDefaultInstance()) return this;
        if (!other.getTime().isEmpty()) {
          time_ = other.time_;
          onChanged();
        }
        if (tracesBuilder_ == null) {
          if (!other.traces_.isEmpty()) {
            if (traces_.isEmpty()) {
              traces_ = other.traces_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTracesIsMutable();
              traces_.addAll(other.traces_);
            }
            onChanged();
          }
        } else {
          if (!other.traces_.isEmpty()) {
            if (tracesBuilder_.isEmpty()) {
              tracesBuilder_.dispose();
              tracesBuilder_ = null;
              traces_ = other.traces_;
              bitField0_ = (bitField0_ & ~0x00000002);
              tracesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTracesFieldBuilder() : null;
            } else {
              tracesBuilder_.addAllMessages(other.traces_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        waveform.Waveform.Stream parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (waveform.Waveform.Stream) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object time_ = "";
      /**
       * <code>string time = 1;</code>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string time = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string time = 1;</code>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string time = 1;</code>
       */
      public Builder clearTime() {
        
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>string time = 1;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        time_ = value;
        onChanged();
        return this;
      }

      private java.util.List<waveform.Waveform.Trace> traces_ =
        java.util.Collections.emptyList();
      private void ensureTracesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          traces_ = new java.util.ArrayList<waveform.Waveform.Trace>(traces_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          waveform.Waveform.Trace, waveform.Waveform.Trace.Builder, waveform.Waveform.TraceOrBuilder> tracesBuilder_;

      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public java.util.List<waveform.Waveform.Trace> getTracesList() {
        if (tracesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(traces_);
        } else {
          return tracesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public int getTracesCount() {
        if (tracesBuilder_ == null) {
          return traces_.size();
        } else {
          return tracesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public waveform.Waveform.Trace getTraces(int index) {
        if (tracesBuilder_ == null) {
          return traces_.get(index);
        } else {
          return tracesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public Builder setTraces(
          int index, waveform.Waveform.Trace value) {
        if (tracesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTracesIsMutable();
          traces_.set(index, value);
          onChanged();
        } else {
          tracesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public Builder setTraces(
          int index, waveform.Waveform.Trace.Builder builderForValue) {
        if (tracesBuilder_ == null) {
          ensureTracesIsMutable();
          traces_.set(index, builderForValue.build());
          onChanged();
        } else {
          tracesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public Builder addTraces(waveform.Waveform.Trace value) {
        if (tracesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTracesIsMutable();
          traces_.add(value);
          onChanged();
        } else {
          tracesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public Builder addTraces(
          int index, waveform.Waveform.Trace value) {
        if (tracesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTracesIsMutable();
          traces_.add(index, value);
          onChanged();
        } else {
          tracesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public Builder addTraces(
          waveform.Waveform.Trace.Builder builderForValue) {
        if (tracesBuilder_ == null) {
          ensureTracesIsMutable();
          traces_.add(builderForValue.build());
          onChanged();
        } else {
          tracesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public Builder addTraces(
          int index, waveform.Waveform.Trace.Builder builderForValue) {
        if (tracesBuilder_ == null) {
          ensureTracesIsMutable();
          traces_.add(index, builderForValue.build());
          onChanged();
        } else {
          tracesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public Builder addAllTraces(
          java.lang.Iterable<? extends waveform.Waveform.Trace> values) {
        if (tracesBuilder_ == null) {
          ensureTracesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, traces_);
          onChanged();
        } else {
          tracesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public Builder clearTraces() {
        if (tracesBuilder_ == null) {
          traces_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          tracesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public Builder removeTraces(int index) {
        if (tracesBuilder_ == null) {
          ensureTracesIsMutable();
          traces_.remove(index);
          onChanged();
        } else {
          tracesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public waveform.Waveform.Trace.Builder getTracesBuilder(
          int index) {
        return getTracesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public waveform.Waveform.TraceOrBuilder getTracesOrBuilder(
          int index) {
        if (tracesBuilder_ == null) {
          return traces_.get(index);  } else {
          return tracesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public java.util.List<? extends waveform.Waveform.TraceOrBuilder> 
           getTracesOrBuilderList() {
        if (tracesBuilder_ != null) {
          return tracesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(traces_);
        }
      }
      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public waveform.Waveform.Trace.Builder addTracesBuilder() {
        return getTracesFieldBuilder().addBuilder(
            waveform.Waveform.Trace.getDefaultInstance());
      }
      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public waveform.Waveform.Trace.Builder addTracesBuilder(
          int index) {
        return getTracesFieldBuilder().addBuilder(
            index, waveform.Waveform.Trace.getDefaultInstance());
      }
      /**
       * <code>repeated .waveform.Trace traces = 2;</code>
       */
      public java.util.List<waveform.Waveform.Trace.Builder> 
           getTracesBuilderList() {
        return getTracesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          waveform.Waveform.Trace, waveform.Waveform.Trace.Builder, waveform.Waveform.TraceOrBuilder> 
          getTracesFieldBuilder() {
        if (tracesBuilder_ == null) {
          tracesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              waveform.Waveform.Trace, waveform.Waveform.Trace.Builder, waveform.Waveform.TraceOrBuilder>(
                  traces_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          traces_ = null;
        }
        return tracesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:waveform.Stream)
    }

    // @@protoc_insertion_point(class_scope:waveform.Stream)
    private static final waveform.Waveform.Stream DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new waveform.Waveform.Stream();
    }

    public static waveform.Waveform.Stream getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Stream>
        PARSER = new com.google.protobuf.AbstractParser<Stream>() {
      @java.lang.Override
      public Stream parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Stream(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Stream> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Stream> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public waveform.Waveform.Stream getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TraceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:waveform.Trace)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 sampling_rate = 1;</code>
     */
    int getSamplingRate();

    /**
     * <code>string starttime = 2;</code>
     */
    java.lang.String getStarttime();
    /**
     * <code>string starttime = 2;</code>
     */
    com.google.protobuf.ByteString
        getStarttimeBytes();

    /**
     * <code>int32 npts = 3;</code>
     */
    int getNpts();

    /**
     * <code>string channel = 4;</code>
     */
    java.lang.String getChannel();
    /**
     * <code>string channel = 4;</code>
     */
    com.google.protobuf.ByteString
        getChannelBytes();

    /**
     * <code>string data = 5;</code>
     */
    java.lang.String getData();
    /**
     * <code>string data = 5;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>string station_code = 6;</code>
     */
    java.lang.String getStationCode();
    /**
     * <code>string station_code = 6;</code>
     */
    com.google.protobuf.ByteString
        getStationCodeBytes();

    /**
     * <code>string p_pick = 7;</code>
     */
    java.lang.String getPPick();
    /**
     * <code>string p_pick = 7;</code>
     */
    com.google.protobuf.ByteString
        getPPickBytes();

    /**
     * <code>string s_pick = 8;</code>
     */
    java.lang.String getSPick();
    /**
     * <code>string s_pick = 8;</code>
     */
    com.google.protobuf.ByteString
        getSPickBytes();

    /**
     * <code>float p_residual = 9;</code>
     */
    float getPResidual();

    /**
     * <code>float s_residual = 10;</code>
     */
    float getSResidual();

    /**
     * <code>float e_s_distance = 11;</code>
     */
    float getESDistance();

    /**
     * <code>string network = 12;</code>
     */
    java.lang.String getNetwork();
    /**
     * <code>string network = 12;</code>
     */
    com.google.protobuf.ByteString
        getNetworkBytes();

    /**
     * <code>string component = 13;</code>
     */
    java.lang.String getComponent();
    /**
     * <code>string component = 13;</code>
     */
    com.google.protobuf.ByteString
        getComponentBytes();

    /**
     * <code>string data_dtype = 14;</code>
     */
    java.lang.String getDataDtype();
    /**
     * <code>string data_dtype = 14;</code>
     */
    com.google.protobuf.ByteString
        getDataDtypeBytes();
  }
  /**
   * Protobuf type {@code waveform.Trace}
   */
  public  static final class Trace extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:waveform.Trace)
      TraceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Trace.newBuilder() to construct.
    private Trace(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Trace() {
      samplingRate_ = 0;
      starttime_ = "";
      npts_ = 0;
      channel_ = "";
      data_ = "";
      stationCode_ = "";
      pPick_ = "";
      sPick_ = "";
      pResidual_ = 0F;
      sResidual_ = 0F;
      eSDistance_ = 0F;
      network_ = "";
      component_ = "";
      dataDtype_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Trace(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              samplingRate_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              starttime_ = s;
              break;
            }
            case 24: {

              npts_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              channel_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              stationCode_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              pPick_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              sPick_ = s;
              break;
            }
            case 77: {

              pResidual_ = input.readFloat();
              break;
            }
            case 85: {

              sResidual_ = input.readFloat();
              break;
            }
            case 93: {

              eSDistance_ = input.readFloat();
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              network_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              component_ = s;
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              dataDtype_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return waveform.Waveform.internal_static_waveform_Trace_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return waveform.Waveform.internal_static_waveform_Trace_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              waveform.Waveform.Trace.class, waveform.Waveform.Trace.Builder.class);
    }

    public static final int SAMPLING_RATE_FIELD_NUMBER = 1;
    private int samplingRate_;
    /**
     * <code>int32 sampling_rate = 1;</code>
     */
    public int getSamplingRate() {
      return samplingRate_;
    }

    public static final int STARTTIME_FIELD_NUMBER = 2;
    private volatile java.lang.Object starttime_;
    /**
     * <code>string starttime = 2;</code>
     */
    public java.lang.String getStarttime() {
      java.lang.Object ref = starttime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        starttime_ = s;
        return s;
      }
    }
    /**
     * <code>string starttime = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStarttimeBytes() {
      java.lang.Object ref = starttime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        starttime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NPTS_FIELD_NUMBER = 3;
    private int npts_;
    /**
     * <code>int32 npts = 3;</code>
     */
    public int getNpts() {
      return npts_;
    }

    public static final int CHANNEL_FIELD_NUMBER = 4;
    private volatile java.lang.Object channel_;
    /**
     * <code>string channel = 4;</code>
     */
    public java.lang.String getChannel() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channel_ = s;
        return s;
      }
    }
    /**
     * <code>string channel = 4;</code>
     */
    public com.google.protobuf.ByteString
        getChannelBytes() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private volatile java.lang.Object data_;
    /**
     * <code>string data = 5;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATION_CODE_FIELD_NUMBER = 6;
    private volatile java.lang.Object stationCode_;
    /**
     * <code>string station_code = 6;</code>
     */
    public java.lang.String getStationCode() {
      java.lang.Object ref = stationCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stationCode_ = s;
        return s;
      }
    }
    /**
     * <code>string station_code = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStationCodeBytes() {
      java.lang.Object ref = stationCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stationCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int P_PICK_FIELD_NUMBER = 7;
    private volatile java.lang.Object pPick_;
    /**
     * <code>string p_pick = 7;</code>
     */
    public java.lang.String getPPick() {
      java.lang.Object ref = pPick_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pPick_ = s;
        return s;
      }
    }
    /**
     * <code>string p_pick = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPPickBytes() {
      java.lang.Object ref = pPick_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pPick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S_PICK_FIELD_NUMBER = 8;
    private volatile java.lang.Object sPick_;
    /**
     * <code>string s_pick = 8;</code>
     */
    public java.lang.String getSPick() {
      java.lang.Object ref = sPick_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sPick_ = s;
        return s;
      }
    }
    /**
     * <code>string s_pick = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSPickBytes() {
      java.lang.Object ref = sPick_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sPick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int P_RESIDUAL_FIELD_NUMBER = 9;
    private float pResidual_;
    /**
     * <code>float p_residual = 9;</code>
     */
    public float getPResidual() {
      return pResidual_;
    }

    public static final int S_RESIDUAL_FIELD_NUMBER = 10;
    private float sResidual_;
    /**
     * <code>float s_residual = 10;</code>
     */
    public float getSResidual() {
      return sResidual_;
    }

    public static final int E_S_DISTANCE_FIELD_NUMBER = 11;
    private float eSDistance_;
    /**
     * <code>float e_s_distance = 11;</code>
     */
    public float getESDistance() {
      return eSDistance_;
    }

    public static final int NETWORK_FIELD_NUMBER = 12;
    private volatile java.lang.Object network_;
    /**
     * <code>string network = 12;</code>
     */
    public java.lang.String getNetwork() {
      java.lang.Object ref = network_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        network_ = s;
        return s;
      }
    }
    /**
     * <code>string network = 12;</code>
     */
    public com.google.protobuf.ByteString
        getNetworkBytes() {
      java.lang.Object ref = network_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        network_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPONENT_FIELD_NUMBER = 13;
    private volatile java.lang.Object component_;
    /**
     * <code>string component = 13;</code>
     */
    public java.lang.String getComponent() {
      java.lang.Object ref = component_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        component_ = s;
        return s;
      }
    }
    /**
     * <code>string component = 13;</code>
     */
    public com.google.protobuf.ByteString
        getComponentBytes() {
      java.lang.Object ref = component_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        component_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_DTYPE_FIELD_NUMBER = 14;
    private volatile java.lang.Object dataDtype_;
    /**
     * <code>string data_dtype = 14;</code>
     */
    public java.lang.String getDataDtype() {
      java.lang.Object ref = dataDtype_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataDtype_ = s;
        return s;
      }
    }
    /**
     * <code>string data_dtype = 14;</code>
     */
    public com.google.protobuf.ByteString
        getDataDtypeBytes() {
      java.lang.Object ref = dataDtype_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataDtype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (samplingRate_ != 0) {
        output.writeInt32(1, samplingRate_);
      }
      if (!getStarttimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, starttime_);
      }
      if (npts_ != 0) {
        output.writeInt32(3, npts_);
      }
      if (!getChannelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, channel_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, data_);
      }
      if (!getStationCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, stationCode_);
      }
      if (!getPPickBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, pPick_);
      }
      if (!getSPickBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, sPick_);
      }
      if (pResidual_ != 0F) {
        output.writeFloat(9, pResidual_);
      }
      if (sResidual_ != 0F) {
        output.writeFloat(10, sResidual_);
      }
      if (eSDistance_ != 0F) {
        output.writeFloat(11, eSDistance_);
      }
      if (!getNetworkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, network_);
      }
      if (!getComponentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, component_);
      }
      if (!getDataDtypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, dataDtype_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (samplingRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, samplingRate_);
      }
      if (!getStarttimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, starttime_);
      }
      if (npts_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, npts_);
      }
      if (!getChannelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, channel_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, data_);
      }
      if (!getStationCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, stationCode_);
      }
      if (!getPPickBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, pPick_);
      }
      if (!getSPickBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, sPick_);
      }
      if (pResidual_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, pResidual_);
      }
      if (sResidual_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, sResidual_);
      }
      if (eSDistance_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(11, eSDistance_);
      }
      if (!getNetworkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, network_);
      }
      if (!getComponentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, component_);
      }
      if (!getDataDtypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, dataDtype_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof waveform.Waveform.Trace)) {
        return super.equals(obj);
      }
      waveform.Waveform.Trace other = (waveform.Waveform.Trace) obj;

      boolean result = true;
      result = result && (getSamplingRate()
          == other.getSamplingRate());
      result = result && getStarttime()
          .equals(other.getStarttime());
      result = result && (getNpts()
          == other.getNpts());
      result = result && getChannel()
          .equals(other.getChannel());
      result = result && getData()
          .equals(other.getData());
      result = result && getStationCode()
          .equals(other.getStationCode());
      result = result && getPPick()
          .equals(other.getPPick());
      result = result && getSPick()
          .equals(other.getSPick());
      result = result && (
          java.lang.Float.floatToIntBits(getPResidual())
          == java.lang.Float.floatToIntBits(
              other.getPResidual()));
      result = result && (
          java.lang.Float.floatToIntBits(getSResidual())
          == java.lang.Float.floatToIntBits(
              other.getSResidual()));
      result = result && (
          java.lang.Float.floatToIntBits(getESDistance())
          == java.lang.Float.floatToIntBits(
              other.getESDistance()));
      result = result && getNetwork()
          .equals(other.getNetwork());
      result = result && getComponent()
          .equals(other.getComponent());
      result = result && getDataDtype()
          .equals(other.getDataDtype());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SAMPLING_RATE_FIELD_NUMBER;
      hash = (53 * hash) + getSamplingRate();
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getStarttime().hashCode();
      hash = (37 * hash) + NPTS_FIELD_NUMBER;
      hash = (53 * hash) + getNpts();
      hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
      hash = (53 * hash) + getChannel().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + STATION_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getStationCode().hashCode();
      hash = (37 * hash) + P_PICK_FIELD_NUMBER;
      hash = (53 * hash) + getPPick().hashCode();
      hash = (37 * hash) + S_PICK_FIELD_NUMBER;
      hash = (53 * hash) + getSPick().hashCode();
      hash = (37 * hash) + P_RESIDUAL_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPResidual());
      hash = (37 * hash) + S_RESIDUAL_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSResidual());
      hash = (37 * hash) + E_S_DISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getESDistance());
      hash = (37 * hash) + NETWORK_FIELD_NUMBER;
      hash = (53 * hash) + getNetwork().hashCode();
      hash = (37 * hash) + COMPONENT_FIELD_NUMBER;
      hash = (53 * hash) + getComponent().hashCode();
      hash = (37 * hash) + DATA_DTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDataDtype().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static waveform.Waveform.Trace parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static waveform.Waveform.Trace parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static waveform.Waveform.Trace parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static waveform.Waveform.Trace parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static waveform.Waveform.Trace parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static waveform.Waveform.Trace parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static waveform.Waveform.Trace parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static waveform.Waveform.Trace parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static waveform.Waveform.Trace parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static waveform.Waveform.Trace parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static waveform.Waveform.Trace parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static waveform.Waveform.Trace parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(waveform.Waveform.Trace prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code waveform.Trace}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:waveform.Trace)
        waveform.Waveform.TraceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return waveform.Waveform.internal_static_waveform_Trace_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return waveform.Waveform.internal_static_waveform_Trace_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                waveform.Waveform.Trace.class, waveform.Waveform.Trace.Builder.class);
      }

      // Construct using waveform.Waveform.Trace.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        samplingRate_ = 0;

        starttime_ = "";

        npts_ = 0;

        channel_ = "";

        data_ = "";

        stationCode_ = "";

        pPick_ = "";

        sPick_ = "";

        pResidual_ = 0F;

        sResidual_ = 0F;

        eSDistance_ = 0F;

        network_ = "";

        component_ = "";

        dataDtype_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return waveform.Waveform.internal_static_waveform_Trace_descriptor;
      }

      @java.lang.Override
      public waveform.Waveform.Trace getDefaultInstanceForType() {
        return waveform.Waveform.Trace.getDefaultInstance();
      }

      @java.lang.Override
      public waveform.Waveform.Trace build() {
        waveform.Waveform.Trace result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public waveform.Waveform.Trace buildPartial() {
        waveform.Waveform.Trace result = new waveform.Waveform.Trace(this);
        result.samplingRate_ = samplingRate_;
        result.starttime_ = starttime_;
        result.npts_ = npts_;
        result.channel_ = channel_;
        result.data_ = data_;
        result.stationCode_ = stationCode_;
        result.pPick_ = pPick_;
        result.sPick_ = sPick_;
        result.pResidual_ = pResidual_;
        result.sResidual_ = sResidual_;
        result.eSDistance_ = eSDistance_;
        result.network_ = network_;
        result.component_ = component_;
        result.dataDtype_ = dataDtype_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof waveform.Waveform.Trace) {
          return mergeFrom((waveform.Waveform.Trace)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(waveform.Waveform.Trace other) {
        if (other == waveform.Waveform.Trace.getDefaultInstance()) return this;
        if (other.getSamplingRate() != 0) {
          setSamplingRate(other.getSamplingRate());
        }
        if (!other.getStarttime().isEmpty()) {
          starttime_ = other.starttime_;
          onChanged();
        }
        if (other.getNpts() != 0) {
          setNpts(other.getNpts());
        }
        if (!other.getChannel().isEmpty()) {
          channel_ = other.channel_;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (!other.getStationCode().isEmpty()) {
          stationCode_ = other.stationCode_;
          onChanged();
        }
        if (!other.getPPick().isEmpty()) {
          pPick_ = other.pPick_;
          onChanged();
        }
        if (!other.getSPick().isEmpty()) {
          sPick_ = other.sPick_;
          onChanged();
        }
        if (other.getPResidual() != 0F) {
          setPResidual(other.getPResidual());
        }
        if (other.getSResidual() != 0F) {
          setSResidual(other.getSResidual());
        }
        if (other.getESDistance() != 0F) {
          setESDistance(other.getESDistance());
        }
        if (!other.getNetwork().isEmpty()) {
          network_ = other.network_;
          onChanged();
        }
        if (!other.getComponent().isEmpty()) {
          component_ = other.component_;
          onChanged();
        }
        if (!other.getDataDtype().isEmpty()) {
          dataDtype_ = other.dataDtype_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        waveform.Waveform.Trace parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (waveform.Waveform.Trace) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int samplingRate_ ;
      /**
       * <code>int32 sampling_rate = 1;</code>
       */
      public int getSamplingRate() {
        return samplingRate_;
      }
      /**
       * <code>int32 sampling_rate = 1;</code>
       */
      public Builder setSamplingRate(int value) {
        
        samplingRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sampling_rate = 1;</code>
       */
      public Builder clearSamplingRate() {
        
        samplingRate_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object starttime_ = "";
      /**
       * <code>string starttime = 2;</code>
       */
      public java.lang.String getStarttime() {
        java.lang.Object ref = starttime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          starttime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string starttime = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStarttimeBytes() {
        java.lang.Object ref = starttime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          starttime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string starttime = 2;</code>
       */
      public Builder setStarttime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        starttime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string starttime = 2;</code>
       */
      public Builder clearStarttime() {
        
        starttime_ = getDefaultInstance().getStarttime();
        onChanged();
        return this;
      }
      /**
       * <code>string starttime = 2;</code>
       */
      public Builder setStarttimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        starttime_ = value;
        onChanged();
        return this;
      }

      private int npts_ ;
      /**
       * <code>int32 npts = 3;</code>
       */
      public int getNpts() {
        return npts_;
      }
      /**
       * <code>int32 npts = 3;</code>
       */
      public Builder setNpts(int value) {
        
        npts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 npts = 3;</code>
       */
      public Builder clearNpts() {
        
        npts_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object channel_ = "";
      /**
       * <code>string channel = 4;</code>
       */
      public java.lang.String getChannel() {
        java.lang.Object ref = channel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          channel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string channel = 4;</code>
       */
      public com.google.protobuf.ByteString
          getChannelBytes() {
        java.lang.Object ref = channel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string channel = 4;</code>
       */
      public Builder setChannel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string channel = 4;</code>
       */
      public Builder clearChannel() {
        
        channel_ = getDefaultInstance().getChannel();
        onChanged();
        return this;
      }
      /**
       * <code>string channel = 4;</code>
       */
      public Builder setChannelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        channel_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 5;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 5;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 5;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 5;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object stationCode_ = "";
      /**
       * <code>string station_code = 6;</code>
       */
      public java.lang.String getStationCode() {
        java.lang.Object ref = stationCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stationCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string station_code = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStationCodeBytes() {
        java.lang.Object ref = stationCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stationCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string station_code = 6;</code>
       */
      public Builder setStationCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stationCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string station_code = 6;</code>
       */
      public Builder clearStationCode() {
        
        stationCode_ = getDefaultInstance().getStationCode();
        onChanged();
        return this;
      }
      /**
       * <code>string station_code = 6;</code>
       */
      public Builder setStationCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stationCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pPick_ = "";
      /**
       * <code>string p_pick = 7;</code>
       */
      public java.lang.String getPPick() {
        java.lang.Object ref = pPick_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pPick_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string p_pick = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPPickBytes() {
        java.lang.Object ref = pPick_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pPick_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string p_pick = 7;</code>
       */
      public Builder setPPick(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pPick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string p_pick = 7;</code>
       */
      public Builder clearPPick() {
        
        pPick_ = getDefaultInstance().getPPick();
        onChanged();
        return this;
      }
      /**
       * <code>string p_pick = 7;</code>
       */
      public Builder setPPickBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pPick_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sPick_ = "";
      /**
       * <code>string s_pick = 8;</code>
       */
      public java.lang.String getSPick() {
        java.lang.Object ref = sPick_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sPick_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string s_pick = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSPickBytes() {
        java.lang.Object ref = sPick_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sPick_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string s_pick = 8;</code>
       */
      public Builder setSPick(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sPick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string s_pick = 8;</code>
       */
      public Builder clearSPick() {
        
        sPick_ = getDefaultInstance().getSPick();
        onChanged();
        return this;
      }
      /**
       * <code>string s_pick = 8;</code>
       */
      public Builder setSPickBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sPick_ = value;
        onChanged();
        return this;
      }

      private float pResidual_ ;
      /**
       * <code>float p_residual = 9;</code>
       */
      public float getPResidual() {
        return pResidual_;
      }
      /**
       * <code>float p_residual = 9;</code>
       */
      public Builder setPResidual(float value) {
        
        pResidual_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float p_residual = 9;</code>
       */
      public Builder clearPResidual() {
        
        pResidual_ = 0F;
        onChanged();
        return this;
      }

      private float sResidual_ ;
      /**
       * <code>float s_residual = 10;</code>
       */
      public float getSResidual() {
        return sResidual_;
      }
      /**
       * <code>float s_residual = 10;</code>
       */
      public Builder setSResidual(float value) {
        
        sResidual_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float s_residual = 10;</code>
       */
      public Builder clearSResidual() {
        
        sResidual_ = 0F;
        onChanged();
        return this;
      }

      private float eSDistance_ ;
      /**
       * <code>float e_s_distance = 11;</code>
       */
      public float getESDistance() {
        return eSDistance_;
      }
      /**
       * <code>float e_s_distance = 11;</code>
       */
      public Builder setESDistance(float value) {
        
        eSDistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float e_s_distance = 11;</code>
       */
      public Builder clearESDistance() {
        
        eSDistance_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object network_ = "";
      /**
       * <code>string network = 12;</code>
       */
      public java.lang.String getNetwork() {
        java.lang.Object ref = network_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          network_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string network = 12;</code>
       */
      public com.google.protobuf.ByteString
          getNetworkBytes() {
        java.lang.Object ref = network_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          network_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string network = 12;</code>
       */
      public Builder setNetwork(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        network_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string network = 12;</code>
       */
      public Builder clearNetwork() {
        
        network_ = getDefaultInstance().getNetwork();
        onChanged();
        return this;
      }
      /**
       * <code>string network = 12;</code>
       */
      public Builder setNetworkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        network_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object component_ = "";
      /**
       * <code>string component = 13;</code>
       */
      public java.lang.String getComponent() {
        java.lang.Object ref = component_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          component_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string component = 13;</code>
       */
      public com.google.protobuf.ByteString
          getComponentBytes() {
        java.lang.Object ref = component_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          component_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string component = 13;</code>
       */
      public Builder setComponent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        component_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string component = 13;</code>
       */
      public Builder clearComponent() {
        
        component_ = getDefaultInstance().getComponent();
        onChanged();
        return this;
      }
      /**
       * <code>string component = 13;</code>
       */
      public Builder setComponentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        component_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dataDtype_ = "";
      /**
       * <code>string data_dtype = 14;</code>
       */
      public java.lang.String getDataDtype() {
        java.lang.Object ref = dataDtype_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataDtype_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data_dtype = 14;</code>
       */
      public com.google.protobuf.ByteString
          getDataDtypeBytes() {
        java.lang.Object ref = dataDtype_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataDtype_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data_dtype = 14;</code>
       */
      public Builder setDataDtype(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataDtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data_dtype = 14;</code>
       */
      public Builder clearDataDtype() {
        
        dataDtype_ = getDefaultInstance().getDataDtype();
        onChanged();
        return this;
      }
      /**
       * <code>string data_dtype = 14;</code>
       */
      public Builder setDataDtypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataDtype_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:waveform.Trace)
    }

    // @@protoc_insertion_point(class_scope:waveform.Trace)
    private static final waveform.Waveform.Trace DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new waveform.Waveform.Trace();
    }

    public static waveform.Waveform.Trace getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Trace>
        PARSER = new com.google.protobuf.AbstractParser<Trace>() {
      @java.lang.Override
      public Trace parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Trace(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Trace> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Trace> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public waveform.Waveform.Trace getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waveform_Stream_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waveform_Stream_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waveform_Trace_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waveform_Trace_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016waveform.proto\022\010waveform\"7\n\006Stream\022\014\n\004" +
      "time\030\001 \001(\t\022\037\n\006traces\030\002 \003(\0132\017.waveform.Tr" +
      "ace\"\212\002\n\005Trace\022\025\n\rsampling_rate\030\001 \001(\005\022\021\n\t" +
      "starttime\030\002 \001(\t\022\014\n\004npts\030\003 \001(\005\022\017\n\007channel" +
      "\030\004 \001(\t\022\014\n\004data\030\005 \001(\t\022\024\n\014station_code\030\006 \001" +
      "(\t\022\016\n\006p_pick\030\007 \001(\t\022\016\n\006s_pick\030\010 \001(\t\022\022\n\np_" +
      "residual\030\t \001(\002\022\022\n\ns_residual\030\n \001(\002\022\024\n\014e_" +
      "s_distance\030\013 \001(\002\022\017\n\007network\030\014 \001(\t\022\021\n\tcom" +
      "ponent\030\r \001(\t\022\022\n\ndata_dtype\030\016 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_waveform_Stream_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_waveform_Stream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waveform_Stream_descriptor,
        new java.lang.String[] { "Time", "Traces", });
    internal_static_waveform_Trace_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_waveform_Trace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waveform_Trace_descriptor,
        new java.lang.String[] { "SamplingRate", "Starttime", "Npts", "Channel", "Data", "StationCode", "PPick", "SPick", "PResidual", "SResidual", "ESDistance", "Network", "Component", "DataDtype", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
