// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: waveform.proto

package waveform;

public final class WaveformOuterClass {
  private WaveformOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WaveformOrBuilder extends
      // @@protoc_insertion_point(interface_extends:waveform.Waveform)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 sampling_rate = 1;</code>
     */
    int getSamplingRate();

    /**
     * <code>string starttime = 2;</code>
     */
    java.lang.String getStarttime();
    /**
     * <code>string starttime = 2;</code>
     */
    com.google.protobuf.ByteString
        getStarttimeBytes();

    /**
     * <code>int32 npts = 3;</code>
     */
    int getNpts();

    /**
     * <code>int32 nchannels = 4;</code>
     */
    int getNchannels();

    /**
     * <code>string data = 5;</code>
     */
    java.lang.String getData();
    /**
     * <code>string data = 5;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>string station_code = 6;</code>
     */
    java.lang.String getStationCode();
    /**
     * <code>string station_code = 6;</code>
     */
    com.google.protobuf.ByteString
        getStationCodeBytes();

    /**
     * <code>string p_pick = 7;</code>
     */
    java.lang.String getPPick();
    /**
     * <code>string p_pick = 7;</code>
     */
    com.google.protobuf.ByteString
        getPPickBytes();

    /**
     * <code>string s_pick = 8;</code>
     */
    java.lang.String getSPick();
    /**
     * <code>string s_pick = 8;</code>
     */
    com.google.protobuf.ByteString
        getSPickBytes();
  }
  /**
   * Protobuf type {@code waveform.Waveform}
   */
  public  static final class Waveform extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:waveform.Waveform)
      WaveformOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Waveform.newBuilder() to construct.
    private Waveform(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Waveform() {
      samplingRate_ = 0;
      starttime_ = "";
      npts_ = 0;
      nchannels_ = 0;
      data_ = "";
      stationCode_ = "";
      pPick_ = "";
      sPick_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Waveform(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              samplingRate_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              starttime_ = s;
              break;
            }
            case 24: {

              npts_ = input.readInt32();
              break;
            }
            case 32: {

              nchannels_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              stationCode_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              pPick_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              sPick_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return waveform.WaveformOuterClass.internal_static_waveform_Waveform_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return waveform.WaveformOuterClass.internal_static_waveform_Waveform_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              waveform.WaveformOuterClass.Waveform.class, waveform.WaveformOuterClass.Waveform.Builder.class);
    }

    public static final int SAMPLING_RATE_FIELD_NUMBER = 1;
    private int samplingRate_;
    /**
     * <code>int32 sampling_rate = 1;</code>
     */
    public int getSamplingRate() {
      return samplingRate_;
    }

    public static final int STARTTIME_FIELD_NUMBER = 2;
    private volatile java.lang.Object starttime_;
    /**
     * <code>string starttime = 2;</code>
     */
    public java.lang.String getStarttime() {
      java.lang.Object ref = starttime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        starttime_ = s;
        return s;
      }
    }
    /**
     * <code>string starttime = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStarttimeBytes() {
      java.lang.Object ref = starttime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        starttime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NPTS_FIELD_NUMBER = 3;
    private int npts_;
    /**
     * <code>int32 npts = 3;</code>
     */
    public int getNpts() {
      return npts_;
    }

    public static final int NCHANNELS_FIELD_NUMBER = 4;
    private int nchannels_;
    /**
     * <code>int32 nchannels = 4;</code>
     */
    public int getNchannels() {
      return nchannels_;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private volatile java.lang.Object data_;
    /**
     * <code>string data = 5;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATION_CODE_FIELD_NUMBER = 6;
    private volatile java.lang.Object stationCode_;
    /**
     * <code>string station_code = 6;</code>
     */
    public java.lang.String getStationCode() {
      java.lang.Object ref = stationCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stationCode_ = s;
        return s;
      }
    }
    /**
     * <code>string station_code = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStationCodeBytes() {
      java.lang.Object ref = stationCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stationCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int P_PICK_FIELD_NUMBER = 7;
    private volatile java.lang.Object pPick_;
    /**
     * <code>string p_pick = 7;</code>
     */
    public java.lang.String getPPick() {
      java.lang.Object ref = pPick_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pPick_ = s;
        return s;
      }
    }
    /**
     * <code>string p_pick = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPPickBytes() {
      java.lang.Object ref = pPick_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pPick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S_PICK_FIELD_NUMBER = 8;
    private volatile java.lang.Object sPick_;
    /**
     * <code>string s_pick = 8;</code>
     */
    public java.lang.String getSPick() {
      java.lang.Object ref = sPick_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sPick_ = s;
        return s;
      }
    }
    /**
     * <code>string s_pick = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSPickBytes() {
      java.lang.Object ref = sPick_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sPick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (samplingRate_ != 0) {
        output.writeInt32(1, samplingRate_);
      }
      if (!getStarttimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, starttime_);
      }
      if (npts_ != 0) {
        output.writeInt32(3, npts_);
      }
      if (nchannels_ != 0) {
        output.writeInt32(4, nchannels_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, data_);
      }
      if (!getStationCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, stationCode_);
      }
      if (!getPPickBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, pPick_);
      }
      if (!getSPickBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, sPick_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (samplingRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, samplingRate_);
      }
      if (!getStarttimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, starttime_);
      }
      if (npts_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, npts_);
      }
      if (nchannels_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, nchannels_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, data_);
      }
      if (!getStationCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, stationCode_);
      }
      if (!getPPickBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, pPick_);
      }
      if (!getSPickBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, sPick_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof waveform.WaveformOuterClass.Waveform)) {
        return super.equals(obj);
      }
      waveform.WaveformOuterClass.Waveform other = (waveform.WaveformOuterClass.Waveform) obj;

      boolean result = true;
      result = result && (getSamplingRate()
          == other.getSamplingRate());
      result = result && getStarttime()
          .equals(other.getStarttime());
      result = result && (getNpts()
          == other.getNpts());
      result = result && (getNchannels()
          == other.getNchannels());
      result = result && getData()
          .equals(other.getData());
      result = result && getStationCode()
          .equals(other.getStationCode());
      result = result && getPPick()
          .equals(other.getPPick());
      result = result && getSPick()
          .equals(other.getSPick());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SAMPLING_RATE_FIELD_NUMBER;
      hash = (53 * hash) + getSamplingRate();
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getStarttime().hashCode();
      hash = (37 * hash) + NPTS_FIELD_NUMBER;
      hash = (53 * hash) + getNpts();
      hash = (37 * hash) + NCHANNELS_FIELD_NUMBER;
      hash = (53 * hash) + getNchannels();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + STATION_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getStationCode().hashCode();
      hash = (37 * hash) + P_PICK_FIELD_NUMBER;
      hash = (53 * hash) + getPPick().hashCode();
      hash = (37 * hash) + S_PICK_FIELD_NUMBER;
      hash = (53 * hash) + getSPick().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static waveform.WaveformOuterClass.Waveform parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static waveform.WaveformOuterClass.Waveform parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static waveform.WaveformOuterClass.Waveform parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static waveform.WaveformOuterClass.Waveform parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static waveform.WaveformOuterClass.Waveform parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static waveform.WaveformOuterClass.Waveform parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static waveform.WaveformOuterClass.Waveform parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static waveform.WaveformOuterClass.Waveform parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static waveform.WaveformOuterClass.Waveform parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static waveform.WaveformOuterClass.Waveform parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static waveform.WaveformOuterClass.Waveform parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static waveform.WaveformOuterClass.Waveform parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(waveform.WaveformOuterClass.Waveform prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code waveform.Waveform}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:waveform.Waveform)
        waveform.WaveformOuterClass.WaveformOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return waveform.WaveformOuterClass.internal_static_waveform_Waveform_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return waveform.WaveformOuterClass.internal_static_waveform_Waveform_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                waveform.WaveformOuterClass.Waveform.class, waveform.WaveformOuterClass.Waveform.Builder.class);
      }

      // Construct using waveform.WaveformOuterClass.Waveform.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        samplingRate_ = 0;

        starttime_ = "";

        npts_ = 0;

        nchannels_ = 0;

        data_ = "";

        stationCode_ = "";

        pPick_ = "";

        sPick_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return waveform.WaveformOuterClass.internal_static_waveform_Waveform_descriptor;
      }

      @java.lang.Override
      public waveform.WaveformOuterClass.Waveform getDefaultInstanceForType() {
        return waveform.WaveformOuterClass.Waveform.getDefaultInstance();
      }

      @java.lang.Override
      public waveform.WaveformOuterClass.Waveform build() {
        waveform.WaveformOuterClass.Waveform result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public waveform.WaveformOuterClass.Waveform buildPartial() {
        waveform.WaveformOuterClass.Waveform result = new waveform.WaveformOuterClass.Waveform(this);
        result.samplingRate_ = samplingRate_;
        result.starttime_ = starttime_;
        result.npts_ = npts_;
        result.nchannels_ = nchannels_;
        result.data_ = data_;
        result.stationCode_ = stationCode_;
        result.pPick_ = pPick_;
        result.sPick_ = sPick_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof waveform.WaveformOuterClass.Waveform) {
          return mergeFrom((waveform.WaveformOuterClass.Waveform)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(waveform.WaveformOuterClass.Waveform other) {
        if (other == waveform.WaveformOuterClass.Waveform.getDefaultInstance()) return this;
        if (other.getSamplingRate() != 0) {
          setSamplingRate(other.getSamplingRate());
        }
        if (!other.getStarttime().isEmpty()) {
          starttime_ = other.starttime_;
          onChanged();
        }
        if (other.getNpts() != 0) {
          setNpts(other.getNpts());
        }
        if (other.getNchannels() != 0) {
          setNchannels(other.getNchannels());
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (!other.getStationCode().isEmpty()) {
          stationCode_ = other.stationCode_;
          onChanged();
        }
        if (!other.getPPick().isEmpty()) {
          pPick_ = other.pPick_;
          onChanged();
        }
        if (!other.getSPick().isEmpty()) {
          sPick_ = other.sPick_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        waveform.WaveformOuterClass.Waveform parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (waveform.WaveformOuterClass.Waveform) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int samplingRate_ ;
      /**
       * <code>int32 sampling_rate = 1;</code>
       */
      public int getSamplingRate() {
        return samplingRate_;
      }
      /**
       * <code>int32 sampling_rate = 1;</code>
       */
      public Builder setSamplingRate(int value) {
        
        samplingRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sampling_rate = 1;</code>
       */
      public Builder clearSamplingRate() {
        
        samplingRate_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object starttime_ = "";
      /**
       * <code>string starttime = 2;</code>
       */
      public java.lang.String getStarttime() {
        java.lang.Object ref = starttime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          starttime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string starttime = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStarttimeBytes() {
        java.lang.Object ref = starttime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          starttime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string starttime = 2;</code>
       */
      public Builder setStarttime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        starttime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string starttime = 2;</code>
       */
      public Builder clearStarttime() {
        
        starttime_ = getDefaultInstance().getStarttime();
        onChanged();
        return this;
      }
      /**
       * <code>string starttime = 2;</code>
       */
      public Builder setStarttimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        starttime_ = value;
        onChanged();
        return this;
      }

      private int npts_ ;
      /**
       * <code>int32 npts = 3;</code>
       */
      public int getNpts() {
        return npts_;
      }
      /**
       * <code>int32 npts = 3;</code>
       */
      public Builder setNpts(int value) {
        
        npts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 npts = 3;</code>
       */
      public Builder clearNpts() {
        
        npts_ = 0;
        onChanged();
        return this;
      }

      private int nchannels_ ;
      /**
       * <code>int32 nchannels = 4;</code>
       */
      public int getNchannels() {
        return nchannels_;
      }
      /**
       * <code>int32 nchannels = 4;</code>
       */
      public Builder setNchannels(int value) {
        
        nchannels_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 nchannels = 4;</code>
       */
      public Builder clearNchannels() {
        
        nchannels_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 5;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 5;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 5;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 5;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object stationCode_ = "";
      /**
       * <code>string station_code = 6;</code>
       */
      public java.lang.String getStationCode() {
        java.lang.Object ref = stationCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stationCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string station_code = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStationCodeBytes() {
        java.lang.Object ref = stationCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stationCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string station_code = 6;</code>
       */
      public Builder setStationCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stationCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string station_code = 6;</code>
       */
      public Builder clearStationCode() {
        
        stationCode_ = getDefaultInstance().getStationCode();
        onChanged();
        return this;
      }
      /**
       * <code>string station_code = 6;</code>
       */
      public Builder setStationCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stationCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pPick_ = "";
      /**
       * <code>string p_pick = 7;</code>
       */
      public java.lang.String getPPick() {
        java.lang.Object ref = pPick_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pPick_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string p_pick = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPPickBytes() {
        java.lang.Object ref = pPick_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pPick_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string p_pick = 7;</code>
       */
      public Builder setPPick(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pPick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string p_pick = 7;</code>
       */
      public Builder clearPPick() {
        
        pPick_ = getDefaultInstance().getPPick();
        onChanged();
        return this;
      }
      /**
       * <code>string p_pick = 7;</code>
       */
      public Builder setPPickBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pPick_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sPick_ = "";
      /**
       * <code>string s_pick = 8;</code>
       */
      public java.lang.String getSPick() {
        java.lang.Object ref = sPick_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sPick_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string s_pick = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSPickBytes() {
        java.lang.Object ref = sPick_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sPick_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string s_pick = 8;</code>
       */
      public Builder setSPick(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sPick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string s_pick = 8;</code>
       */
      public Builder clearSPick() {
        
        sPick_ = getDefaultInstance().getSPick();
        onChanged();
        return this;
      }
      /**
       * <code>string s_pick = 8;</code>
       */
      public Builder setSPickBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sPick_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:waveform.Waveform)
    }

    // @@protoc_insertion_point(class_scope:waveform.Waveform)
    private static final waveform.WaveformOuterClass.Waveform DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new waveform.WaveformOuterClass.Waveform();
    }

    public static waveform.WaveformOuterClass.Waveform getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Waveform>
        PARSER = new com.google.protobuf.AbstractParser<Waveform>() {
      @java.lang.Override
      public Waveform parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Waveform(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Waveform> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Waveform> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public waveform.WaveformOuterClass.Waveform getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waveform_Waveform_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waveform_Waveform_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016waveform.proto\022\010waveform\"\231\001\n\010Waveform\022" +
      "\025\n\rsampling_rate\030\001 \001(\005\022\021\n\tstarttime\030\002 \001(" +
      "\t\022\014\n\004npts\030\003 \001(\005\022\021\n\tnchannels\030\004 \001(\005\022\014\n\004da" +
      "ta\030\005 \001(\t\022\024\n\014station_code\030\006 \001(\t\022\016\n\006p_pick" +
      "\030\007 \001(\t\022\016\n\006s_pick\030\010 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_waveform_Waveform_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_waveform_Waveform_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waveform_Waveform_descriptor,
        new java.lang.String[] { "SamplingRate", "Starttime", "Npts", "Nchannels", "Data", "StationCode", "PPick", "SPick", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
