# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waveform.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='waveform.proto',
  package='waveform',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12seismic_data.proto\x12\x08waveform\"S\n\x08Waveform\x12\x15\n\rsampling_rate\x18\x01 \x01(\x05\x12\x11\n\tstarttime\x18\x02 \x01(\t\x12\x0f\n\x07nsample\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\tb\x06proto3')
)




_WAVEFORM = _descriptor.Descriptor(
  name='Waveform',
  full_name='waveform.Waveform',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sampling_rate', full_name='waveform.Waveform.sampling_rate', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='starttime', full_name='waveform.Waveform.starttime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nsample', full_name='waveform.Waveform.nsample', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='waveform.Waveform.data', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['Waveform'] = _WAVEFORM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Waveform = _reflection.GeneratedProtocolMessageType('Waveform', (_message.Message,), dict(
  DESCRIPTOR = _WAVEFORM,
  __module__ = 'seismic_data_pb2'
  # @@protoc_insertion_point(class_scope:waveform.Waveform)
  ))
_sym_db.RegisterMessage(Waveform)


# @@protoc_insertion_point(module_scope)
