[default]

picker1.snr_threshold = 6
picker1.residual_tolerance = 15e-3
picker1.p_s_tolerance = 5e-3
picker1.waveform_filter.frequency_min = 100
picker1.waveform_filter.frequency_max = 1000
picker1.p_wave.search_window.start = -100e-3
picker1.p_wave.search_window.end = 20e-3
picker1.p_wave.search_window.resolution = 0.001
picker1.p_wave.snr_window.noise = 0.005
picker1.p_wave.snr_window.signal = 0.01
picker1.s_wave.search_window.start = -100e-3
picker1.s_wave.search_window.end = 20e-3
picker1.s_wave.search_window.resolution = 0.001
picker1.s_wave.snr_window.noise = 0.005
picker1.s_wave.snr_window.signal = 0.01

picker2.snr_threshold = 6
picker2.residual_tolerance = 15e-3
picker2.p_s_tolerance = 5e-3
picker2.waveform_filter.frequency_min = 50
picker2.waveform_filter.frequency_max = 500
picker2.p_wave.search_window.start = -100e-3
picker2.p_wave.search_window.end = 20e-3
picker2.p_wave.search_window.resolution = 0.001
picker2.p_wave.snr_window.noise = 0.01
picker2.p_wave.snr_window.signal = 0.02
picker2.s_wave.search_window.start = -100e-3
picker2.s_wave.search_window.end = 20e-3
picker2.s_wave.search_window.resolution = 0.001
picker2.s_wave.snr_window.noise = 0.01
picker2.s_wave.snr_window.signal = 0.02

picker3.snr_threshold = 6
picker3.residual_tolerance = 15e-3
picker3.p_s_tolerance = 5e-3
picker3.output_data_name  = 'picks_set'
picker3.log_topic = 'automatic picker'
picker3.log_file_name = 'automatic_picker.log'
picker3.waveform_filter.frequency_min = 20
picker3.waveform_filter.frequency_max = 200
picker3.p_wave.search_window.start = -100e-3
picker3.p_wave.search_window.end = 20e-3
picker3.p_wave.search_window.resolution = 0.001
picker3.p_wave.snr_window.noise = 0.02
picker3.p_wave.snr_window.signal = 0.04
picker3.s_wave.search_window.start = -100e-3
picker3.s_wave.search_window.end = 20e-3
picker3.s_wave.search_window.resolution = 0.001
picker3.s_wave.snr_window.noise = 0.02
picker3.s_wave.snr_window.signal = 0.04


